Mathew development
MathewLG/software-product-sprint pull request #2
Opened 2021-02-24 22:41 UTC by MathewLG

2021-02-25 05:45 UTC, nnooney requested changes
Your website looks great! I've added some comments; please let me know if you have any questions about the comments.

2021-02-25 05:45 UTC, nnooney commented on portfolio/src/main/webapp/index.html
> +      <p>My name is Mathew Lopez, I am computer science student at Tec de Monterrey. <br>
Is the `<br>` tags necessary for the paragraph? I haven't seen them used too often in HTML code, because the browser can automatically choose where to add them in a paragraph based on the width of the screen or other container. Another reason not to include line breaks is that websites are often viewed on multiple devices of different sizes, and it could result in jarring paragraphs on smaller screens.

One thing I like to do is use the Chrome DevTools to preview a website at different screen sizes: https://developers.google.com/web/tools/chrome-devtools/device-mode. Note that you can open DevTools by right clicking and selecting Inspect, pressing Ctrl+Shift+I, or selecting the three dots->More Tools->Developer Tools.

2021-02-25 05:45 UTC, nnooney commented on portfolio/src/main/webapp/index.html
> +          <p>
HTML technically requires only `<li>` tags as direct descendants of `<ul>` tags. I recommend moving this paragraph to within the `<li>` so it looks like this:

```
<ul>
    <li>
        <h3>Title</h3>
        <p>Paragraph text with an image: <img /></p>
    </li>
...
</ul>
```

Web browsers will try their best to render any HTML presented to it (they aren't as strict as some other programming tools), so the current code will still render nicely.

2021-02-25 05:45 UTC, nnooney commented on portfolio/src/main/webapp/index.html
> +          <img src="images/bogota.jpg" alt="Bogota Landscape" width = "600" height="400">
HTML attributes generally do not have spaces surrounding the "=" sign (several attributes in this section have extra spaces).

2021-02-25 05:45 UTC, nnooney commented on portfolio/src/main/webapp/index.html
> +    <!--<p>Click <a href="/hello">here</a> to see content created by server code.</p>-->
It's good practice not to leave commented-out code in the final version of a file; this can be confusing and add extra noise to the file.

2021-02-25 05:45 UTC, nnooney commented on portfolio/src/main/webapp/script.js
> +  const quotes =
Nice quotes! I have to catch up on Mr. Robot :)

2021-02-25 05:45 UTC, nnooney commented on portfolio/src/main/webapp/style.css
> +button{
Is your intent to center the button? If that is the case, I like using https://css-tricks.com/centering-css-complete-guide/ to guide me. Buttons are `inline-block` elements by default, so using text-align: center is enough, and the margin styles may not be necessary. Of course, if there's other reasons to keep the margin, then please do keep them.

2021-02-25 05:45 UTC, nnooney commented on portfolio/src/main/webapp/style.css
> +body{
One overall comment about the styles:

Generally, large complex websites will use many HTML elements in many different parts of the site. They often use the attributes `id` or `class` on an element in the HTML file, and then use the `#id` or `.class` selectors in a CSS file to provide the styles. The benefit of this is that you can use the same element but apply a different style to it.

2021-02-27 00:21 UTC, MathewLG commented on portfolio/src/main/webapp/index.html
> +      <p>My name is Mathew Lopez, I am computer science student at Tec de Monterrey. <br>
Done, dev tools were very helpful

2021-02-27 00:21 UTC, MathewLG commented on portfolio/src/main/webapp/index.html
> +          <p>
Done

2021-02-27 00:21 UTC, MathewLG commented on portfolio/src/main/webapp/index.html
> +          <img src="images/bogota.jpg" alt="Bogota Landscape" width = "600" height="400">
Done

2021-02-27 00:22 UTC, MathewLG commented on portfolio/src/main/webapp/index.html
> +    <!--<p>Click <a href="/hello">here</a> to see content created by server code.</p>-->
Done

2021-02-27 00:22 UTC, MathewLG commented on portfolio/src/main/webapp/style.css
> +button{
Done, thanks for the resources, helped me a lot

2021-02-27 00:22 UTC, MathewLG commented on portfolio/src/main/webapp/style.css
> +body{
Done

2021-02-27 00:30 UTC, nnooney approved these changes
LGTM

2021-02-27 00:37 UTC, merged